// ~100 largest US companies (close to the S&P 100), grouped by GICS sector.
// approxCap = market cap in $bn from Finnhub on 2026-10-04 — only used until live caps load.
export interface UniverseStock {
  symbol: string
  name: string
  sector: string
  approxCap: number
}

export const MARKET_UNIVERSE: UniverseStock[] = [
  { symbol: 'AAPL', name: 'Apple Inc', sector: 'Information Technology', approxCap: 4869.9 },
  { symbol: 'MSFT', name: 'Microsoft Corp', sector: 'Information Technology', approxCap: 3842.9 },
  { symbol: 'NVDA', name: 'NVIDIA Corp', sector: 'Information Technology', approxCap: 5638.2 },
  { symbol: 'AVGO', name: 'Broadcom Inc', sector: 'Information Technology', approxCap: 1695.3 },
  { symbol: 'ORCL', name: 'Oracle Corp', sector: 'Information Technology', approxCap: 430.3 },
  { symbol: 'CRM', name: 'Salesforce Inc', sector: 'Information Technology', approxCap: 193.1 },
  { symbol: 'ADBE', name: 'Adobe Inc', sector: 'Information Technology', approxCap: 92.5 },
  { symbol: 'AMD', name: 'Advanced Micro Devices Inc', sector: 'Information Technology', approxCap: 1034.8 },
  { symbol: 'CSCO', name: 'Cisco Systems Inc', sector: 'Information Technology', approxCap: 442.4 },
  { symbol: 'ACN', name: 'Accenture PLC', sector: 'Information Technology', approxCap: 121.7 },
  { symbol: 'IBM', name: 'International Business Machines Corp', sector: 'Information Technology', approxCap: 209.8 },
  { symbol: 'INTC', name: 'Intel Corp', sector: 'Information Technology', approxCap: 630.8 },
  { symbol: 'INTU', name: 'Intuit Inc', sector: 'Information Technology', approxCap: 75.1 },
  { symbol: 'NOW', name: 'ServiceNow Inc', sector: 'Information Technology', approxCap: 138.9 },
  { symbol: 'QCOM', name: 'Qualcomm Inc', sector: 'Information Technology', approxCap: 194.2 },
  { symbol: 'TXN', name: 'Texas Instruments Inc', sector: 'Information Technology', approxCap: 268.3 },
  { symbol: 'PLTR', name: 'Palantir Technologies Inc', sector: 'Information Technology', approxCap: 453.6 },
  { symbol: 'GOOGL', name: 'Alphabet Inc', sector: 'Communication Services', approxCap: 4201.0 },
  { symbol: 'META', name: 'Meta Platforms Inc', sector: 'Communication Services', approxCap: 1854.8 },
  { symbol: 'NFLX', name: 'Netflix Inc', sector: 'Communication Services', approxCap: 279.2 },
  { symbol: 'CMCSA', name: 'Comcast Corp', sector: 'Communication Services', approxCap: 76.5 },
  { symbol: 'CHTR', name: 'Charter Communications Inc', sector: 'Communication Services', approxCap: 19.1 },
  { symbol: 'DIS', name: 'Walt Disney Co', sector: 'Communication Services', approxCap: 176.5 },
  { symbol: 'T', name: 'AT&T Inc', sector: 'Communication Services', approxCap: 166.5 },
  { symbol: 'TMUS', name: 'T-Mobile US Inc', sector: 'Communication Services', approxCap: 175.5 },
  { symbol: 'VZ', name: 'Verizon Communications Inc', sector: 'Communication Services', approxCap: 190.6 },
  { symbol: 'AMZN', name: 'Amazon.com Inc', sector: 'Consumer Discretionary', approxCap: 2713.0 },
  { symbol: 'TSLA', name: 'Tesla Inc', sector: 'Consumer Discretionary', approxCap: 1463.7 },
  { symbol: 'HD', name: 'Home Depot Inc', sector: 'Consumer Discretionary', approxCap: 282.2 },
  { symbol: 'LOW', name: "Lowe's Companies Inc", sector: 'Consumer Discretionary', approxCap: 101.4 },
  { symbol: 'MCD', name: "McDonald's Corp", sector: 'Consumer Discretionary', approxCap: 164.1 },
  { symbol: 'NKE', name: 'Nike Inc', sector: 'Consumer Discretionary', approxCap: 50.2 },
  { symbol: 'SBUX', name: 'Starbucks Corp', sector: 'Consumer Discretionary', approxCap: 108.0 },
  { symbol: 'BKNG', name: 'Booking Holdings Inc', sector: 'Consumer Discretionary', approxCap: 119.5 },
  { symbol: 'GM', name: 'General Motors Co', sector: 'Consumer Discretionary', approxCap: 68.7 },
  { symbol: 'F', name: 'Ford Motor Co', sector: 'Consumer Discretionary', approxCap: 48.2 },
  { symbol: 'WMT', name: 'Walmart Inc', sector: 'Consumer Staples', approxCap: 884.1 },
  { symbol: 'COST', name: 'Costco Wholesale Corp', sector: 'Consumer Staples', approxCap: 408.1 },
  { symbol: 'PG', name: 'Procter & Gamble Co', sector: 'Consumer Staples', approxCap: 336.6 },
  { symbol: 'KO', name: 'Coca-Cola Co', sector: 'Consumer Staples', approxCap: 368.5 },
  { symbol: 'PEP', name: 'PepsiCo Inc', sector: 'Consumer Staples', approxCap: 171.8 },
  { symbol: 'PM', name: 'Philip Morris International Inc', sector: 'Consumer Staples', approxCap: 292.2 },
  { symbol: 'MO', name: 'Altria Group Inc', sector: 'Consumer Staples', approxCap: 112.5 },
  { symbol: 'MDLZ', name: 'Mondelez International Inc', sector: 'Consumer Staples', approxCap: 74.3 },
  { symbol: 'CL', name: 'Colgate-Palmolive Co', sector: 'Consumer Staples', approxCap: 67.2 },
  { symbol: 'TGT', name: 'Target Corp', sector: 'Consumer Staples', approxCap: 70.9 },
  { symbol: 'LLY', name: 'Eli Lilly and Co', sector: 'Health Care', approxCap: 1075.8 },
  { symbol: 'UNH', name: 'UnitedHealth Group Inc', sector: 'Health Care', approxCap: 333.8 },
  { symbol: 'JNJ', name: 'Johnson & Johnson', sector: 'Health Care', approxCap: 617.0 },
  { symbol: 'ABBV', name: 'AbbVie Inc', sector: 'Health Care', approxCap: 464.4 },
  { symbol: 'MRK', name: 'Merck & Co Inc', sector: 'Health Care', approxCap: 356.0 },
  { symbol: 'ABT', name: 'Abbott Laboratories', sector: 'Health Care', approxCap: 168.7 },
  { symbol: 'TMO', name: 'Thermo Fisher Scientific Inc', sector: 'Health Care', approxCap: 242.1 },
  { symbol: 'DHR', name: 'Danaher Corp', sector: 'Health Care', approxCap: 150.5 },
  { symbol: 'AMGN', name: 'Amgen Inc', sector: 'Health Care', approxCap: 217.9 },
  { symbol: 'PFE', name: 'Pfizer Inc', sector: 'Health Care', approxCap: 158.5 },
  { symbol: 'BMY', name: 'Bristol-Myers Squibb Co', sector: 'Health Care', approxCap: 124.9 },
  { symbol: 'GILD', name: 'Gilead Sciences, Inc', sector: 'Health Care', approxCap: 179.5 },
  { symbol: 'ISRG', name: 'Intuitive Surgical Inc', sector: 'Health Care', approxCap: 138.5 },
  { symbol: 'MDT', name: 'Medtronic PLC', sector: 'Health Care', approxCap: 110.5 },
  { symbol: 'CVS', name: 'CVS Health Corp', sector: 'Health Care', approxCap: 110.6 },
  { symbol: 'BRK.B', name: 'Berkshire Hathaway Inc', sector: 'Financials', approxCap: 967.8 },
  { symbol: 'JPM', name: 'JPMorgan Chase & Co', sector: 'Financials', approxCap: 883.5 },
  { symbol: 'V', name: 'Visa Inc', sector: 'Financials', approxCap: 673.4 },
  { symbol: 'MA', name: 'Mastercard Inc', sector: 'Financials', approxCap: 483.8 },
  { symbol: 'BAC', name: 'Bank of America Corp', sector: 'Financials', approxCap: 375.9 },
  { symbol: 'WFC', name: 'Wells Fargo & Co', sector: 'Financials', approxCap: 258.3 },
  { symbol: 'GS', name: 'Goldman Sachs Group Inc', sector: 'Financials', approxCap: 262.8 },
  { symbol: 'MS', name: 'Morgan Stanley', sector: 'Financials', approxCap: 298.9 },
  { symbol: 'C', name: 'Citigroup Inc', sector: 'Financials', approxCap: 215.6 },
  { symbol: 'AXP', name: 'American Express Co', sector: 'Financials', approxCap: 204.5 },
  { symbol: 'BLK', name: 'BlackRock Inc', sector: 'Financials', approxCap: 172.2 },
  { symbol: 'SCHW', name: 'Charles Schwab Corp', sector: 'Financials', approxCap: 167.2 },
  { symbol: 'BK', name: 'Bank of New York Mellon Corp', sector: 'Financials', approxCap: 70.0 },
  { symbol: 'COF', name: 'Capital One Financial Corp', sector: 'Financials', approxCap: 119.5 },
  { symbol: 'MET', name: 'MetLife Inc', sector: 'Financials', approxCap: 60.0 },
  { symbol: 'AIG', name: 'American International Group Inc', sector: 'Financials', approxCap: 39.2 },
  { symbol: 'USB', name: 'US Bancorp', sector: 'Financials', approxCap: 89.6 },
  { symbol: 'PYPL', name: 'PayPal Holdings Inc', sector: 'Financials', approxCap: 45.2 },
  { symbol: 'GE', name: 'General Electric Co', sector: 'Industrials', approxCap: 321.2 },
  { symbol: 'CAT', name: 'Caterpillar Inc', sector: 'Industrials', approxCap: 388.6 },
  { symbol: 'RTX', name: 'RTX Corp', sector: 'Industrials', approxCap: 248.9 },
  { symbol: 'HON', name: 'Honeywell International Inc', sector: 'Industrials', approxCap: 67.8 },
  { symbol: 'UNP', name: 'Union Pacific Corp', sector: 'Industrials', approxCap: 165.3 },
  { symbol: 'UPS', name: 'United Parcel Service Inc', sector: 'Industrials', approxCap: 79.1 },
  { symbol: 'BA', name: 'Boeing Co', sector: 'Industrials', approxCap: 153.0 },
  { symbol: 'LMT', name: 'Lockheed Martin Corp', sector: 'Industrials', approxCap: 116.6 },
  { symbol: 'DE', name: 'Deere & Co', sector: 'Industrials', approxCap: 185.2 },
  { symbol: 'GD', name: 'General Dynamics Corp', sector: 'Industrials', approxCap: 89.3 },
  { symbol: 'MMM', name: '3M Co', sector: 'Industrials', approxCap: 83.5 },
  { symbol: 'FDX', name: 'FedEx Corp', sector: 'Industrials', approxCap: 68.7 },
  { symbol: 'EMR', name: 'Emerson Electric Co', sector: 'Industrials', approxCap: 90.1 },
  { symbol: 'UBER', name: 'Uber Technologies Inc', sector: 'Industrials', approxCap: 139.1 },
  { symbol: 'XOM', name: 'Exxonmobil Holdings Corp', sector: 'Energy', approxCap: 650.6 },
  { symbol: 'CVX', name: 'Chevron Corp', sector: 'Energy', approxCap: 408.4 },
  { symbol: 'COP', name: 'ConocoPhillips', sector: 'Energy', approxCap: 152.3 },
  { symbol: 'NEE', name: 'Nextera Energy Inc', sector: 'Utilities', approxCap: 160.3 },
  { symbol: 'SO', name: 'Southern Co', sector: 'Utilities', approxCap: 96.3 },
  { symbol: 'DUK', name: 'Duke Energy Corp', sector: 'Utilities', approxCap: 89.0 },
  { symbol: 'AMT', name: 'American Tower Corp', sector: 'Real Estate', approxCap: 75.6 },
  { symbol: 'SPG', name: 'Simon Property Group Inc', sector: 'Real Estate', approxCap: 65.0 },
  { symbol: 'LIN', name: 'Linde PLC', sector: 'Materials', approxCap: 221.0 },
]

/** Index ETFs shown above the heat map. */
export const INDEX_ETFS = [
  { symbol: 'SPY', name: 'S&P 500' },
  { symbol: 'QQQ', name: 'Nasdaq 100' },
  { symbol: 'DIA', name: 'Dow 30' },
  { symbol: 'IWM', name: 'Russell 2000' },
]
